const ARTICLES = {
    ARTICLES_LOAD: "ARTICLES_LOAD",
    ARTICLES_LOAD_FAIL: "ARTICLES_LOAD_FAIL",
    ARTICLES_LOAD_SUCCESS: "ARTICLES_LOAD_SUCCESS",

    ARTICLE_DELETE_PENDING: "ARTICLE_DELETE_PENDING",
    ARTICLE_DELETE_SUCCESS: "ARTICLE_DELETE_SUCCESS",
    ARTICLE_DELETE_FAIL: "ARTICLE_DELETE_FAIL",

    ARTICLE_ADD_PENDING: "ARTICLE_ADD_PENDING",
    ARTICLE_ADD_SUCCESS: "ARTICLE_ADD_SUCCESS",
    ARTICLE_ADD_FAIL: "ARTICLE_ADD_FAIL"
};

export { ARTICLES };

const ARTICLE = {
    LOAD_ONE_ARTICLE: "LOAD_ONE_ARTICLE",
    LOAD_ONE_ARTICLE_SUCCESS: "LOAD_ONE_ARTICLE_SUCCESS",
    LOAD_ONE_ARTICLE_FAIL: "LOAD_ONE_ARTICLE_FAIL"
};

export { ARTICLE }

const COMMENTS = {
    COMMENTS_LOAD_SUCCESS: "COMMENTS_LOAD_SUCCESS",
    COMMENTS_LOAD_FAIL: "COMMENTS_LOAD_FAIL",
    COMMENTS_LOAD_PENDING: "COMMENTS_LOAD",

    ADD_COMMENT_PENDING: "ADD_COMMENT",
    ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
    ADD_COMMENT_FAIL: "ADD_COMMENT_FAIL",

    COMMENT_DELETE_SUCCESS: "COMMENT_DELETE_SUCCESS",
    COMMENT_DELETE_FAIL: "COMMENT_DELETE_FAIL",
    COMMENT_DELETE_PENDING: "COMMENT_DELETE_PENDING"
};
export { COMMENTS }

const PAGE = {

    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SET_CURRENT_PAGE_PENDING: "SET_CURRENT_PAGE_PENDING",
    SET_CURRENT_PAGE_FAIL: "SET_CURRENT_PAGE_FAIL",

    SET_TOTAL_PAGES: "SET_TOTAL_PAGES",
    SET_TOTAL_PAGES_PENDING: "SET_TOTAL_PAGES_PENDING",
    SET_TOTAL_PAGES_FAIL: "SET_TOTAL_PAGES_FAIL"
}
export { PAGE }
